baseURL = "https://wemakeuofmhappen.netlify.app/"
languageCode = "en-us"
title = "We make UofM happen"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    
[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "We are a group of Early Career Researchers at the University of Manitoba."
    meta_og_title = "We make UofM happen"
    meta_og_type = "website"
    meta_og_url = "https://wemakeuofmhappen.ca"

[[menu.main]]
	name = "What we do"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Who we are"
    url = "/people/"
    weight = 2

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
